#!/bin/bash

folder=$2

if [ "x$folder" = "x" ]; then
    echo "Need a third argument - a folder to init"
    exit 2
fi

if [ -d $folder ]; then
    echo "Folder exists. Please remove it."
    exit 1
fi

mkdir $folder
cd $folder
mkdir {archive,config,incoming,tacklebox,scripts}

echo "Skel created."

POPDIR=`pwd`

S_ROOT=/usr/share/monomoy/skel
cd $S_ROOT
files=$(find . -type f)
cd $POPDIR

echo "Copying in skel files."

for file in $files; do
    cp $S_ROOT/$file $file -v
done
