#!/usr/bin/env python

from monomoy.archive import MonomoyArchive
from monomoy.core import db

archive = MonomoyArchive("./archive")
for package in archive.get_packages():
    archive.remove_package(package['_id'])
