#!/usr/bin/env python

from monomoy.changes import parse_changes_file
from monomoy.archive import MonomoyArchive


archive = MonomoyArchive("./archive")
for package in archive.get_packages():
    print "  ({_id})   {name}/{version}".format(**package)
