#!/usr/bin/env python
from monomoy.core import db
import json
import sys


obj = json.load(open(sys.argv[2], 'r'))
for key in obj:
    deebee = getattr(db, key)
    for thing in obj[key]:
        eyedee = deebee.insert(thing, safe=True)
        print " -> %s/%s" % (key, eyedee)
