#!/usr/bin/env python

from monomoy.changes import parse_changes_file
from monomoy.archive import MonomoyArchive
from monomoy.utils import iter_dir_xtn


archive = MonomoyArchive(".")
for package in iter_dir_xtn('incoming', '.changes'):
    changes = parse_changes_file(package, directory='incoming')
    archive.process_incoming_package(changes)
