#!/usr/bin/env python

import sys
import json

from monomoy.archive import MonomoyArchive
from monomoy.utils import JSONEncoder

args = sys.argv[2:]
if args == []:
    print "Need package id"

archive = MonomoyArchive('.')
obj = archive.get_package(args[0])
print json.dumps(obj, sort_keys=True, indent=4, cls=JSONEncoder)
